name: Baloto Bot Auto

on:
  schedule:
# 6:00 AM Colombia (11:00 AM UTC) los Martes, Jueves y Domingos
    - cron: '0 11 * * 0,2,4'
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run Baloto Bot Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py

- name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add baloto.db
        git commit -m "Actualizar base de datos con nuevo sorteo" || echo "No hay cambios"
        git push          
